### ISSUE TITLE
I am having about 6 errors after implementing your authentication code on my xamarin cross platform project

### ISSUE THREAD

**Issue by aproko234** [hnicolus/Xamarin-Forms-Firebase-Authentication-#1]
1. In the Android Project, it is complaining about this line (public class FirebaseAuthenticator : IFirebaseAuthenticator) in the MainActivity.cs as follows: (Error	CS0246	The type or namespace name 'IFirebaseAuthenticator' could not be found (are you missing a using directive or an assembly reference?))
2. In the iOS Project, it is complaining about this line (public class FirebaseAuthenticator : IFirebaseAuthenticator) in the AppDelegate.cs as follows: (Error	CS0246	The type or namespace name 'IFirebaseAuthenticator' could not be found (are you missing a using directive or an assembly reference?))
3. It appears not to be seeing the IFireBaseAuthenticator which I put in my shared app startup module like this 
using AbuseAlert.Views;
using System;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace AbuseAlert
{
    public partial class AppShell : Xamarin.Forms.Shell
    {
        public AppShell()
        {
            InitializeComponent();
            Routing.RegisterRoute(nameof(ItemDetailPage), typeof(ItemDetailPage));
            Routing.RegisterRoute(nameof(NewItemPage), typeof(NewItemPage));
        }

        private async void OnMenuItemClicked(object sender, EventArgs e)
        {
            await Shell.Current.GoToAsync("//LoginPage");
        }
    }
}

namespace AbuseAlert.Interfaces.FirebaseAuthentication
{
    public interface IFirebaseAuthenticator
    {
        Task<string> SignInWithEmailAndPasswordAsync(string email, string password);
        Task<string> SignUpWithEmailPasswordAsync(string email, string password);
        Task ForgotPasswordAsync(string email);
    }
}

4. So, what's the issue?

**Comment by nicksoftware** [comment]
Hi , you should add the namespace which   IFirebaseAuthenticator  interface is located in...

The great news is the process has now been simplified since last i  created this demo

all you need now is to install the  `FirebaseAuthentication.net` library .then you can write a class like this  : 

```
using System;
using System.Threading.Tasks;
using Firebase.Auth;
using Newtonsoft.Json;
using Xamarin.Essentials;

namespace YourApp.Services
{


    public class FirebaseAuthenticationService 
    {
        private readonly string API_KEY = "YOUR_API_KEY";
        private readonly FirebaseAuthProvider authProvider;
        public const string AUTH_TOKEN_STORAGE_KEY = "YourAppUserAuthToken";

        public FirebaseAuthenticationService()
        {
            authProvider = new FirebaseAuthProvider(new FirebaseConfig(API_KEY));
        }

        public async Task LoginAsync(string username, string password)
        {
            try
            {
                var auth = await authProvider.SignInWithEmailAndPasswordAsync(username, password);
                var content =await auth.GetFreshAuthAsync();
                var serializedContent = JsonConvert.SerializeObject(content);
                Preferences.Set(AUTH_TOKEN_STORAGE_KEY, serializedContent);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task RegisterAsync(string email, string password)
        {
            try
            {
                var auth = await authProvider.CreateUserWithEmailAndPasswordAsync(email, password);
                await LoginAsync(email, password);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private async Task RefreshToken()
        {
            try
            {
                var authToken = JsonConvert
                    .DeserializeObject<FirebaseAuth>(Preferences.Get(AUTH_TOKEN_STORAGE_KEY,""));
                var refreshedContent = await authProvider.RefreshAuthAsync(authToken);
                Preferences.Set(AUTH_TOKEN_STORAGE_KEY, JsonConvert.SerializeObject(refreshedContent));

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task<FirebaseAuth> GetUserInformationAsync()
        {
            try
            {
                await RefreshToken();
                return JsonConvert.DeserializeObject<FirebaseAuth>(Preferences.Get(AUTH_TOKEN_STORAGE_KEY, null));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}
```
